package common

const (
	MESSAGE_TYPE_FOR_CLIENT_SERVER_WITH_CLIENT_IPS = "MESSAGE_TYPE_FOR_CLIENT_SERVER_WITH_CLIENT_IPS" //给服务侧的客户端返回客户侧的ip列表
	MESSAGE_TYPE_FOR_CLIENT_CLIENT_WITH_SERVER_IPS = "MESSAGE_TYPE_FOR_CLIENT_CLIENT_WITH_SERVER_IPS" //给客户侧的客户端返回服务侧的ip列表。单个
	MESSAGE_TYPE_KEEP_ALIVE                        = "MESSAGE_TYPE_KEEP_ALIVE"                        //心跳 保活
)

